[package]
name = "rust_brain"
version = "0.1.0"
edition = "2018"

[dependencies]

[lib]
name = "rust_brain"
crate-type = ["dylib"]

[dependencies.cpython]
version = "0.5"
features = ["extension-module"]
