FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    gcc \
    gcc-mingw-w64 \
    gcc-multilib \
    cmake \
    make \
    clang \
    clang-tidy \
    clang-format \
    valgrind \
    gcovr \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

CMD ["./scripts/build.sh"]
