[package]
name = "conditional_prios"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustlogic = "0.2.0"
wasm-bindgen = "0.2.80"
