apiVersion: apps/v1
kind: Deployment
metadata:
  name: fonseca-de-com
  labels:
    app: fonseca-de-com
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fonseca-de-com
  template:
    metadata:
      labels:
        app: fonseca-de-com 
    spec:
      containers:
      - name: fonseca-de-com
        image: angelalonso/fonseca-de-com:v0.2
        ports:
        - containerPort: 80
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 50
