apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fonseca-de-com
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: fonseca.de.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: fonseca-de-com
              port:
                number: 80
    - host: www.fonseca.de.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: fonseca-de-com
              port:
                number: 80
